### ISSUE TITLE
Feature Request: Accept both

### ISSUE THREAD

**Issue by rechenberger** [pprice/vscode-better-merge#10]
Simple Feature and often needed. This feature would just remove the `<<< HEAD`, `===`, `>>> somebranch` lines.

Including it in the current System could mean:
- Decorator
- `Accept both` - `Alt+M, 3`
- `Accept all both`

**Comment by pprice** [comment]
Yep, great idea. I'll add this today.

**Comment by pprice** [comment]
Added feature in version 0.5.0
