### ISSUE TITLE
Extension stops working after first file is handled

### ISSUE THREAD

**Issue by digitaltopo** [pprice/vscode-better-merge#15]
First off, thank you for this awesome extension!

I'm having an issue where at first the extension seems to be working great, but after accepting a change in a file and continuing with the rebase/merge, subsequent files lack the extension's features, and conflicts just go back to the default appearance without the accept incoming/current links. At that time, non of the commands work from the command palette either. Restarting vscode doesn't seem to help, but if I abort the rebase/merge and start over, the extension starts working again until I go to the next file.

Maybe I'm missing something, but I see no errors in the output in vscode either. Would appreciate any help and please let me know if you need any other info to debug.

```
VSCODE 
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
Ubuntu 16.04

**Comment by pprice** [comment]
Looking into this.

**Comment by pprice** [comment]
Hi @digitaltopo, I've not been able to reproduce this - do you still experience this behavior?

**Comment by pprice** [comment]
Closing. @digitaltopo, please re-open against Microsoft/vscode if this issue persists.
