### ISSUE TITLE
Does not appear on conflicts in vscode 1.11.1

### ISSUE THREAD

**Issue by DasJott** [pprice/vscode-better-merge#16]
Today I had a conflict and the helpful disdplays of this addon didn't appear :(

**Comment by tylerlindell** [comment]
really like using this tool but it is not prompting me to accept changes after merge in VS Code v1.11.1

I have checked out a branch, merged another one into the current one and there are merge conflicts with <<<<<HEAD messages in the code but nothing from Better Merge trying to help with the changes

**Comment by pprice** [comment]
This should be fixed in version 0.6.0.
