### ISSUE TITLE
Consistent action button placement

### ISSUE THREAD

**Issue by deepu105** [pprice/vscode-better-merge#21]
A very nice extension.

I have a small quirk from a UX perspective. I think it would be nice to have a consistent order for the accept* buttons. I see that they keep shuffling between conflicts. I'm using version 0.6.1 with latest vscode (v1.11.2)
![image](https://cloud.githubusercontent.com/assets/1107223/25578935/7daa4b8e-2e73-11e7-8273-607f53318e72.png)

**Comment by pprice** [comment]
Fixed by #22, by @eamodio
