### ISSUE TITLE
diff3 support

### ISSUE THREAD

**Issue by spiffytech** [pprice/vscode-better-merge#23]
Hello! Please add support for the diff3 conflict format. Thanks!

**Comment by pprice** [comment]
Hi @spiffytech 

I've been thinking about how to support different "providers" - do you use diff3 within a particular folder (e.g. workspace) in VSCode or on loose files? 

My current thinking is to have some configuration that can be set on a global or per workspace scope. 
 
 `better-merge.format` - being either `git`, `diff3`, `svn` or whatever. 

A better version of this would be if I could query the open workspaces SCM provider from vscode, so we could do something like.

 `better-merge.format.fallback` - Use this format if we can't detect one 
 `better-merge.format` - Defaults to `auto`, but can be overridden

The last option would be to scan all files for all formats, but I think this would be error prone, and potentially CPU hungry. 

Thoughts?

**Comment by pprice** [comment]
See https://github.com/Microsoft/vscode/issues/25838

**Comment by spiffytech** [comment]
I use diff3 as my global git default, across many projects. My use is always inside git project folders.

I prefer some form of detection better to a global default, but I'd rather have a global default than wait a while if detection is complicated.`

As far as detection goes, you check if the root folder root has a `.git`/`.whatever-else` and ask the VCS for its configuration (ask `git config`), rather than wait until we can ask VS Code.

Alternatively, for diff3 specifically, better-merge already finds the conflicts because they have the `<<<<<<<`/`>>>>>>>` header/footer. It just doesn't correctly handle the `|||||||` section.

That suggests a more efficient detection method: detect regular conflicts, then check each to see if they're diff3 conflicts.

So you have a bunch of options, with different amounts of work and hackyness, depending on tradeoffs of what's possible today + how grand your final vision is.

**Comment by pprice** [comment]
Right, this makes sense. I'm hoping I can have a flow like this at some future point: 
 
 - Ask Vscode what SCM provider is active, hand off to some SCM specific "detector" 
 - For git (once detected), for config, hand off some "detector" implementation
 - Detector, detects regions and lights up commands / codelenses 
 - Use that for the lifetime of the open workspace, start over with workspace. 

I think this is doable, and I don't *need* to wait for vscode api updates. 

As a more tactical fix for diff3, I can just add detection for this within the `<<<<<<` block as you mention. Question: Would you ever want to "Accept" the merged common ancestors, and how would you expect "accept both" to behave?

**Comment by spiffytech** [comment]
It's unlikely I'd want to accept the common ancestor. It's just there for context.

I'd expect 'accept both' to accept the current and incoming change, and ignore the ancestor.

**Comment by pprice** [comment]
@katemihalikova has submitted a PR for the vscode version of this extension. 🎉
