### ISSUE TITLE
Congrats on being put "in the box"!

### ISSUE THREAD

**Issue by eamodio** [pprice/vscode-better-merge#26]
Cool to see this awesome extension bundled with vscode now! (How'd ya pull that one off?) ;)

**Comment by pprice** [comment]
Thanks @eamodio! The team reached out to me last week about merging the extension, so I was all for it. I work at Microsoft, so it was awesome to go over to Redmond and spend the day with the team, meet them and work on merging the code in. 

Thanks for your contributions to the extension, and for the PR to fix the compare changes title in the vscode code base 👍
