### ISSUE TITLE
Support GNU patch --merge results

### ISSUE THREAD

**Issue by RReverser** [pprice/vscode-better-merge#28]
GNU patch's `--merge` is useful when you need to apply external patch but want to see conflicts inline instead of separate `.rej` files.

It produces outputs like following:

```
<<<<<<<
first content
=======
second content
>>>>>>>
```

They're largely similar to Git's own format, except don't have additional information.

As a workaround, if I add just in the end of both `<<<<<<<` and `>>>>>>>`, Better Merge can already recognize it, but it would be nice to have this built-in.

**Comment by RReverser** [comment]
(for what it's worth, I'm already using updated VSCode where this extension is built-in, but thought this is still a more appropriate place to report issues)

**Comment by pprice** [comment]
Hi @RReverser, thanks for pointing this out. It should be an easy change the scanner (which has a different implementation in the vscode 'official' version of the extension). See: https://github.com/Microsoft/vscode/blob/master/extensions/merge-conflict/src/mergeConflictParser.ts#L9 

Currently `startHeaderMarker` and `endFooterMarker` expect a ` `, but this can be changed. We can also update https://github.com/Microsoft/vscode/blob/master/extensions/merge-conflict/src/mergeConflictParser.ts#L9 to take into account that the spaced was not matched. 

Could you re-open the issue up in Microsoft/vscode ?

**Comment by RReverser** [comment]
@pprice Ok sure.

Thanks for updating README btw, it's now more obvious where to report issues. You might want to consider disabling Issues tab on this repo too :)

**Comment by RReverser** [comment]
Tracked in https://github.com/Microsoft/vscode/issues/28360

**Comment by pprice** [comment]
Awesome, thanks! I'll disable issues too.
