### ISSUE TITLE
Doesn't start on Ubuntu and latest VSCode insiders

### ISSUE THREAD

**Issue by tinovyatkin** [pprice/vscode-better-merge#6]
Extension works fine in MacOs, but unfortunately fails to start on Linux with latest VSCode insiders:
![selection_001](https://cloud.githubusercontent.com/assets/5350898/20868158/1da119e6-ba2b-11e6-9afc-d96c5a8db654.png)

**Comment by pprice** [comment]
Ahh, pretty sure this is wrong casing for the import file name. I will put out a fix shortly. Thanks for grabbing the callstack!

On Dec 4, 2016, at 10:08 AM, Tino Vyatkin <notifications@github.com<mailto:notifications@github.com>> wrote:


Extension works fine in MacOs, but unfortunately fails to start on Linux with latest VSCode insiders:
[selection_001]<https://cloud.githubusercontent.com/assets/5350898/20868158/1da119e6-ba2b-11e6-9afc-d96c5a8db654.png>

-

**Comment by pprice** [comment]
Fixed with #7. Updated version 0.3.1 published to vscode marketplace.

**Comment by tinovyatkin** [comment]
Just to confirm that it works fine now, thank you for fast fix!
