### ISSUE TITLE
Terminology of Ours vs Theirs

### ISSUE THREAD

**Issue by eamodio** [pprice/vscode-better-merge#8]
First off -- love the extension!

But I'm finding the terminology of `Ours` vs `Theirs` in the extension a bit confusing (or at least causes me to exert mental energy to reconcile). For merging in code, that terminology could make sense, but with stashes and even rebase it feels odd.

I wonder if talking about the 2 sets would be better served by, "Working Tree" (or maybe "Working Changes" or "Current Changes") and "Incoming Changes"

Thoughts?

**Comment by pprice** [comment]
Thanks!

I've gotten this feedback from other people too, so I'm down for changing. The "ours" vs "theirs" is more old-school terminology for centralized VC, for git it's not *always* applicable (local branch, or stash merge, etc), however they are also names of [git-merge strategies](https://git-scm.com/docs/merge-strategies). 

Couple of things I'm thinking: 

 - The code lenses (the little links above the merge conflict block), could be named after the actual source, so they could be "Accept HEAD | Accept feature-1", which I think leads to less ambiguity. 
 - The commands in the command palette can't be renamed (that i know of), as they are declared at extension registration time via the `package.json`, so these could either be: 
    - Accept 1st change, Accept 2nd change 
    - Accept Current Change (etc...), Accept Incoming Change 

I really like the "Incoming Change" naming, so let's stick with that. I think "Current change" best describes "ours". I will have to rename the `better-merge.accept.current` command (accepts the change the editor cursor is within), to something like `better-merge.accept.cursor-selection`.

Thoughts?

**Comment by eamodio** [comment]
Sounds great -- I think using "Current Change" and "Incoming Change" will go a really long way to reducing confusion. I also like the idea of having the CodeLens adapt more dynamically, but I would recommend not replacing the Current vs Incoming, but augment it. Like "Accept Current (HEAD) change" and "Accept Incoming (feature-1) Change" or something along those lines -- to reinforce the current vs incoming terms when using the commands and/or menus.

**Comment by pprice** [comment]
Sounds good! Agree re: CodeLens naming, I'll get to making these changes.

**Comment by pprice** [comment]
Released update 0.4.0 to the marketplace with these changes.
